spring:
  data:
    mongodb:
      uri: ${NOTEMASTER_DATABASE_URI}
      database: ${NOTEMASTER_DATABASE}
security:
  oauth2:
    resource:
      filter-order: 3
  jwt:
    grant-type: password
    scope-read: read
    scope-write: write
    resource-ids: notemaster